name: deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version: ["5.1.5", "5.2.4", "5.3.5", "5.4.1"]

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.lua-version }}
        luaCompileFlags: LUA_CFLAGS="-fPIC"

    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: install dependencies
      run: |
        luarocks install yuescript

    - name: build
      run: |
        yue luapack.yue
        lua luapack.lua luapack.lua
    
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: luapack.packed.lua
